export const items = [
    { id: 'one', title: 'Pride and Prejudice', author: 'Jane Austen' },
    { id: 'two', title: 'Moby-Dick', author: 'Herman Melville' },
    { id: 'three', title: '1984', author: 'George Orwell' },
    { id: 'four', title: 'The Great Gatsby', author: 'F. Scott Fitzgerald' },
    { id: 'five', title: 'War and Peace', author: 'Leo Tolstoy' },
    { id: 'six', title: 'Crime and Punishment', author: 'Fyodor Dostoevsky' },
    { id: 'seven', title: 'Jane Eyre', author: 'Charlotte Brontë' },
    { id: 'eight', title: 'Wuthering Heights', author: 'Emily Brontë' },
    { id: 'nine', title: 'To Kill a Mockingbird', author: 'Harper Lee' },
    { id: 'ten', title: 'The Odyssey', author: 'Homer' },
    { id: 'eleven', title: 'Brave New World', author: 'Aldous Huxley' },
    { id: 'twelve', title: 'Anna Karenina', author: 'Leo Tolstoy' },
    { id: 'thirteen', title: 'The Catcher in the Rye', author: 'J.D. Salinger' },
    { id: 'fourteen', title: 'Frankenstein', author: 'Mary Shelley' },
    { id: 'fifteen', title: 'The Picture of Dorian Gray', author: 'Oscar Wilde' },
    { id: 'sixteen', title: 'Don Quixote', author: 'Miguel de Cervantes' },
    { id: 'seventeen', title: 'Great Expectations', author: 'Charles Dickens' },
    { id: 'eighteen', title: 'The Brothers Karamazov', author: 'Fyodor Dostoevsky' },
    { id: 'nineteen', title: 'Dracula', author: 'Bram Stoker' },
    { id: 'twenty', title: 'The Iliad', author: 'Homer' },
];